#TODO - Identify and compile source file automatic
CC=gcc
CFLAGS=-Wall -Werror -Wextra -g
ROOT_DIR=$(realpath .)

LIST_FILES = pilha.c

all:
	$(CC) $(CFLAGS) $(LIST_FILES) -o valores_na_pilha

clean:
	rm valores_na_pilha
