#TODO - Identify and compile source file automatic
CC=gcc
CFLAGS=-Wall -Werror -Wextra -g
ROOT_DIR=$(realpath .)

LIST_FILES = jogo.c

all:
	$(CC) $(CFLAGS) $(LIST_FILES) -o jogo_da_velha

clean:
	rm jogo_da_velha
